#!/usr/bin/tcsh

#Section #1:
#set echo
set cutfl = "c1-4 --complement"

#Section #1.5:
if ( ( $1 == n )&&( -e lake )&&( -e ../lake )&&( ! -e ~/_/i/i/preserver )) then
  grep ~/PA1/explanatoryWalkthrough.txt -eswim -C2 | cut -$cutfl > ~/_/die
  exit 4
endif    

#Section #2:
if ( -d $1 ) then
   #It is the locked door. It needs to get a second chance, in PA3.sh.
   echo You must type a 3 digit combination code to enter this room.
   echo -n "Enter it here: "
   set X = $<:q
   if ( x$X == x418 ) then
      chmod 766 w
      cd w
      if ( ! -e ~/_/i/i/lamp ) then
         grep ~/PA3/expl*Walkthrough.txt -elikely|cut -$cutfl|tee ~/_/grue de*
	 exit 1
      endif
   else
      echo Sorry, that combination is incorrect.&& exit 0
   endif

#Section #3:
else if ( ( -e $1 ) || ( -l $1 ) ) then
   echo You cannot go that way. && exit 0
else
   basename `pwd`|tr sundew ndsuwe | xargs expr $1 \!= >&~/X && echo You cannot go that way. && exit 0
   cd ..
endif

#Section 3.5:
#At this point, we know it's a backtrack. But we may be going into the dark.
if ( ! ( ( -e ~/_/i/i/lamp ) || ( -e lamp ) || ( x`pwd | egrep -egRoom/\?e\?$ -enw/s` != x ) ) ) then 
   grep ~/PA1/explana*Walkthrough.txt -elikely|cut -$cutfl|tee ~/_/grue > de*
endif
if ( -e w/cable ) chmod 400 w

#Section #4:
head -n `ls [19]` de*&&mv 9 1 >&~/X
grep -hw `ls -d *| paste ~/_/es -` -h ~/_/T*|cut -d\; -f1
exit 3
