#!/usr/bin/tcsh
#set echo
set cutfl = "c1-4 --complement"
set j = `pwd -P`
set i = `basename $j`
set myroom = `head -1 description`
set real = `realpath $1`
set realbase = `basename $real`
set x = `basename $j | tr "nsweud" "snewdu"`
set lenrealbase = `echo $realbase | wc -m`
if ( X$1 == Xw && "X$myroom" == XNorth\ end\ of\ cave\ passage ) then
echo "You must type a 3 digit combination code to enter this room."
echo -n "Enter it here: "
set keynum = $<
	if ( X$keynum == X418 )then 
	chmod 755 ./w
	cd w
		if (! -e ~/_/i/i/lamp )then
		grep ~/PA3/expl*Walkthrough.txt -elikely|cut -$cutfl|tee de*
		exit 1
		endif
	else
	echo "Sorry, that combination is incorrect." && exit 0
	endif
else if ((! -l $1) && ! -d $1 && $x != $1) then
echo "You cannot go that way." && exit 0
else
basename `pwd -P` | tr "nsweud" "snewdu" | xargs -i expr {} != $1 > ~/X && echo "You cannot go that way." && exit 0
test $lenrealbase -ge 4 > ~/X && echo "You cannot go that way." && exit 0
cd `pwd -P`/..
endif
head -n `ls [19]` de* && mv 9 1 >& ~/X
grep -hw `ls -d * | paste ~/_/es -` -h ~/_/T*|cut -d\; -f1
exit 3
